import { Inter } from "next/font/google";
import "./globals.css";
import Nav from './nav'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trove",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav/>
      <div className="children">
          {children}
        </div>
      </body>
    </html>
  );
}
export const revalidate = 60;